name: manc_dictionary
description: "Mancunian Dictionary"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  freezed_annotation: ^3.1.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true